### ISSUE TITLE
Node 12 support

### ISSUE THREAD

**Issue by drwpow** [siddharthkp/bundlesize#303]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Running `npm i -D bundlesize` on Node 12 (`12.1.0`) results in the following error:

```
../src/dec/stream_decode.cc:14:72: error: no matching member function for call to 'ToObject'
    Local<Object> dictionary = Nan::Get(params, key).ToLocalChecked()->ToObject();
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/Users/drew/.node-gyp/12.1.0/include/node/v8.h:2532:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/drew/.node-gyp/12.1.0/include/node/v8.h:2546:35: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
                    Local<Object> ToObject(Isolate* isolate) const);
                                  ^
../src/dec/stream_decode.cc:40:49: error: no matching member function for call to 'ToObject'
  StreamDecode* obj = new StreamDecode(info[0]->ToObject());
                                       ~~~~~~~~~^~~~~~~~
/Users/drew/.node-gyp/12.1.0/include/node/v8.h:2532:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/drew/.node-gyp/12.1.0/include/node/v8.h:2546:35: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
                    Local<Object> ToObject(Isolate* isolate) const);
                                  ^
../src/dec/stream_decode.cc:48:35: error: no matching member function for call to 'ToObject'
  Local<Object> buffer = info[0]->ToObject();
                         ~~~~~~~~~^~~~~~~~
/Users/drew/.node-gyp/12.1.0/include/node/v8.h:2532:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/drew/.node-gyp/12.1.0/include/node/v8.h:2546:35: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
                    Local<Object> ToObject(Isolate* isolate) const);
                                  ^
../src/dec/stream_decode.cc:54:16: error: no matching member function for call to 'BooleanValue'
  if (info[2]->BooleanValue()) {
      ~~~~~~~~~^~~~~~~~~~~~
/Users/drew/.node-gyp/12.1.0/include/node/v8.h:2559:8: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
  bool BooleanValue(Isolate* isolate) const;
       ^
/Users/drew/.node-gyp/12.1.0/include/node/v8.h:2562:51: note: candidate function not viable: requires single argument 'context', but no arguments were provided
                V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(
                                                  ^
../src/dec/stream_decode.cc:70:16: error: no matching member function for call to 'BooleanValue'
  if (info[1]->BooleanValue()) {
      ~~~~~~~~~^~~~~~~~~~~~
/Users/drew/.node-gyp/12.1.0/include/node/v8.h:2559:8: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
  bool BooleanValue(Isolate* isolate) const;
       ^
/Users/drew/.node-gyp/12.1.0/include/node/v8.h:2562:51: note: candidate function not viable: requires single argument 'context', but no arguments were provided
                V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(
                                                  ^
5 errors generated.
make: *** [Release/obj.target/iltorb/src/dec/stream_decode.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/drew/.nodenv/versions/12.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/Users/drew/.nodenv/versions/12.1.0/bin/node" "/Users/drew/.nodenv/versions/12.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/drew/Sites/manifoldco/ui/node_modules/iltorb
gyp ERR! node -v v12.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN acorn-jsx@5.0.1 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN happo.io@3.14.0 requires a peer of babel-core@^6.0.0 || ^7.0.0-0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iltorb@1.3.10 install: `detect-libc prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iltorb@1.3.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/drew/.npm/_logs/2019-05-11T18_49_56_080Z-debug.log
```

**Additional info**
I tried deleting my `~/.node-gyp` directory, and reinstalling, and still get the error when installing bundlesize.

I have a feeling `node-gyp@4.x.x` is required to run on Node v12, but not sure.

**Comment by siddharthkp** [comment]
Hi 👋 

Couldn't figure out what was wrong, but here's what worked for me:

1. remove `engine` restriction in `package.json` for `bundlesize's@0.17.0`

2. Followed the instructions here: https://github.com/npm/npm/issues/16556#issuecomment-299736206

**Comment by lukelindsey** [comment]
@siddharthkp my guess it updating `brotli-size` is what did it given that it depends on `iltorb` which is what was failing in the above error message. Works for me now though, thanks!

**Comment by siddharthkp** [comment]
Ah, that make sense. Great!

**Comment by petetnt** [comment]
When Node 8 is EOL we could update `brotli-size` which now requires Node 10 which would solve this for good (its still an issue)

**Comment by siddharthkp** [comment]
@petetnt Makes sense

**Comment by tims-j** [comment]
Can this be revisited again now? Node 8 has stopped receiving support from December 31, 2019.

We're currently using bundle size in our Jenkins CI to enforce performance targets of our app and would love to move to Node v14.15.1 but am getting the issue above.

This is because the current version of bundle-size uses a version of `brotli-size` that doesn't support Node Version > 10, In version 3.x of `brotli-size` they have added support for Node > 10.16.0. see https://github.com/erwinmombay/brotli-size/releases/tag/3.0.0

**Comment by cvbuelow** [comment]
I second this. I would like to upgrade to node v14 but can't because of this.

**Comment by siddharthkp** [comment]
I'm working on a new version (1.0.0) of bundlesize that fixes all of these problems.

To not break any of the applications that use bundlesize with npx or with `@latest`, I'm building in a separate bundlesize2 repo + app (until it's ready) 

If you'd like you can try it out: https://github.com/siddharthkp/bundlesize2

Migration path: 
1. Use the npm package `bundlesize2` instead of `bundlesize`
2. If you'd like status reported back to github, use the flag `--enable-github-checks` + authorize bundlesize2 app. [More in the docs](https://github.com/siddharthkp/bundlesize2#build-status-and-checks-for-github)
3. If anything breaks, let me know :)

Note: This is only until the new version is ready and then it will be merged back in this project as a major release

**Comment by tims-j** [comment]
> If you'd like you can try it out: https://github.com/siddharthkp/bundlesize2

Thanks for the that! Is there much difference between bundlesize2 and the beta branch for the current project. I ended up pulling down the beta branch as a dependency instead and everything is working fine so far. 

If you suggest to use bundlesize2 instead though, i'll happily give it a go.

**Comment by siddharthkp** [comment]
Most of the other fixes are in bundlesize2, that's the active development repo

**Comment by cvbuelow** [comment]
thanks, `bundlesize2` is working fine for me. that fixes the issue.
