### ISSUE TITLE
Error running Bundlesize in Jenkins CI

### ISSUE THREAD

**Issue by nikilok** [siddharthkp/bundlesize#305]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
I see this error message in the CI, when running bundlesize.
`
> bundlesize

module.js:682

  return process.dlopen(module, path._makeLong(filename));

                 ^

Error: The module '/home/jenkins/workspace/<BRANCH NAME>/node_modules/iltorb/build/bindings/iltorb.node'

was compiled against a different Node.js version using

NODE_MODULE_VERSION 64. This version of Node.js requires

NODE_MODULE_VERSION 57. Please try re-compiling or re-installing

the module (for instance, using `npm rebuild` or `npm install`).

    at Object.Module._extensions..node (module.js:682:18)

    at Module.load (module.js:566:32)

    at tryModuleLoad (module.js:506:12)

    at Function.Module._load (module.js:498:3)

    at Module.require (module.js:597:17)

    at require (internal/module.js:11:18)

    at Object.<anonymous> (/home/jenkins/workspace/<BRANCH NAME>/node_modules/iltorb/index.js:10:40)

    at Module._compile (module.js:653:30)

    at Object.Module._extensions..js (module.js:664:10)

    at Module.load (module.js:566:32)

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! <project name>@0.1.0 bundlesize:ci: `bundlesize`

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the <project name>@0.1.0 bundlesize:ci script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

npm ERR!     /home/jenkins/.npm/_logs/2019-05-21T15_07_44_798Z-debug.log

sh: line 1:  2473 Terminated              sleep 3

script returned exit code 1
`
**If the current behavior is a bug, please provide the steps to reproduce.**
In my package.json I have the following config.
`"bundlesize": [
    {
      "path": "./build/static/js/*.chunk.js",
      "maxSize": "55 kB",
      "compression": "gzip"
    },
    {
      "path": "./build/static/css/*.chunk.css",
      "maxSize": "3 kB",
      "compression": "gzip"
    }
  ],`

I have a script in package.json as follows to execute bundlesize.
`"bundlesize:ci": "bundlesize",`

I have installed the following version of bundlesize.
` "devDependencies": {
    "bundlesize": "^0.17.2",
     ...
`

**What is the expected behavior?**
I expect bundlesize to run within in the CI env. It runs without any issues on the local machine.
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information.**
- node version: Node v 10
- npm version
- Operating system: Linux
- bundlesize version: ^0.17.2
- CI you are using: Jenkins

**Comment by nikilok** [comment]
I figured out that the issue was that npm install was being done outside the jenkins build machine causing the node mismatch. Could solve the issue by doing an npm install inside the build pipeline.
