### ISSUE TITLE
Comparison with master does not work

### ISSUE THREAD

**Issue by iGitScor** [siddharthkp/bundlesize#96]
Hi,

I installed bundlesize in a travis CI build script but it does not output master nor in the detail or in the success message.

![image](https://user-images.githubusercontent.com/2276944/29269767-94a6df78-80f3-11e7-93eb-471d2ef8dd9c.png)

<img width="370" alt="capture d ecran 2017-08-14 a 13 24 54" src="https://user-images.githubusercontent.com/2276944/29269836-00f25c98-80f4-11e7-9311-5aa6f453b2b6.png">

Here the part of the script for `bundlesize`
```js
/* eslint-disable no-console */

const Build = require('github-build');

const data = {
  repo: process.env.TRAVIS_REPO_SLUG,
  sha: process.env.TRAVIS_COMMIT,
  token: process.env.BUNDLESIZE_GITHUB_TOKEN,
  label: 'bundlesize',
  description: 'Check application size',
};

/* Create a build */
const build = new Build(data);

/* When you call start, a pending status get's added on github (returns a promise) */
build
  .pass()
  .then(() => console.log('Check if a pending status was added'))
  .catch(response => console.log(response.status, response.error.message));

```

Do you have any idea ?

Thank you ! 😄

**Comment by siddharthkp** [comment]
Hi this usually means the values for master were not set. 

Has a pull request been merged after enabling bundlesize?

**Comment by iGitScor** [comment]
Yes, several pull requests were merged in master between (all of them without value for master)

Maybe it doesn't work with fork pull request ?

**Comment by siddharthkp** [comment]
Hmm, that's weird.

Can you run bundlesize with the `--debug` flag and share the output with me?

**Comment by iGitScor** [comment]
Hi,

Yes I can do it

**Comment by iGitScor** [comment]
```
 WARN  cli config: undefined 

 WARN  package json config: [
  {
    "path": "./web/asset/prod/site.js",
    "maxSize": "15 Kb"
  },
  {
    "path": "./web/asset/prod/site.css",
    "maxSize": "15 Kb"
  },
  {
    "path": "./web/asset/prod/checkout.js",
    "maxSize": "15 Kb"
  },
  {
    "path": "./web/asset/prod/checkout.css",
    "maxSize": "15 Kb"
  }
] 

 WARN  selected config: [
  {
    "path": "./web/asset/prod/site.js",
    "maxSize": "15 Kb"
  },
  {
    "path": "./web/asset/prod/site.css",
    "maxSize": "15 Kb"
  },
  {
    "path": "./web/asset/prod/checkout.js",
    "maxSize": "15 Kb"
  },
  {
    "path": "./web/asset/prod/checkout.css",
    "maxSize": "15 Kb"
  }
] 

 WARN  files: [
  {
    "maxSize": 15360,
    "path": "./web/asset/prod/site.js",
    "size": 5978
  },
  {
    "maxSize": 15360,
    "path": "./web/asset/prod/site.css",
    "size": 7772
  },
  {
    "maxSize": 15360,
    "path": "./web/asset/prod/checkout.js",
    "size": 2144
  },
  {
    "maxSize": 15360,
    "path": "./web/asset/prod/checkout.css",
    "size": 9712
  }
] 

 WARN  token exists: false 

 WARN  repo: undefined 

 WARN  sha: undefined 

 WARN  api enabled: false 

 PASS  ./web/asset/prod/site.js: 5.84kB < maxSize 15kB gzip 

 WARN  message: "./web/asset/prod/site.js: 5.84kB < maxSize 15kB gzip" 

 PASS  ./web/asset/prod/site.css: 7.59kB < maxSize 15kB gzip 

 WARN  message: "./web/asset/prod/site.css: 7.59kB < maxSize 15kB gzip" 

 PASS  ./web/asset/prod/checkout.js: 2.09kB < maxSize 15kB gzip 

 WARN  message: "./web/asset/prod/checkout.js: 2.09kB < maxSize 15kB gzip" 

 PASS  ./web/asset/prod/checkout.css: 9.48kB < maxSize 15kB gzip 

 WARN  message: "./web/asset/prod/checkout.css: 9.48kB < maxSize 15kB gzip" 

 WARN  url: "https://bundlesize-store.now.sh/build?info=%7B%22files%22%3A%5B%7B%22maxSize%22%3A15360%2C%22path%22%3A%22.%2Fweb%2Fasset%2Fprod%2Fsite.js%22%2C%22size%22%3A5978%7D%2C%7B%22maxSize%22%3A15360%2C%22path%22%3A%22.%2Fweb%2Fasset%2Fprod%2Fsite.css%22%2C%22size%22%3A7772%7D%2C%7B%22maxSize%22%3A15360%2C%22path%22%3A%22.%2Fweb%2Fasset%2Fprod%2Fcheckout.js%22%2C%22size%22%3A2144%7D%2C%7B%22maxSize%22%3A15360%2C%22path%22%3A%22.%2Fweb%2Fasset%2Fprod%2Fcheckout.css%22%2C%22size%22%3A9712%7D%5D%7D" 

 WARN  global message: undefined 
```

**Comment by siddharthkp** [comment]
Whoops! 

```
WARN  token exists: false 
```

It could not find the token

1. Is it set in environment variables of your CI? 
2. If yes, are you running the command inside a container which does not have access to the CI's environment variables?

**Comment by iGitScor** [comment]
My bad, I launch the command on my machine.
But yes, Travis has those variables. I'll try to launch the command in Travis and send you the debug

Thank you

**Comment by iGitScor** [comment]
```
WARN  cli config: undefined 

 WARN  package json config: [
  {
    "path": "./web/asset/prod/site.js",
    "maxSize": "15 Kb"
  },
  {
    "path": "./web/asset/prod/site.css",
    "maxSize": "15 Kb"
  },
  {
    "path": "./web/asset/prod/checkout.js",
    "maxSize": "15 Kb"
  },
  {
    "path": "./web/asset/prod/checkout.css",
    "maxSize": "15 Kb"
  }
] 

 WARN  selected config: [
  {
    "path": "./web/asset/prod/site.js",
    "maxSize": "15 Kb"
  },
  {
    "path": "./web/asset/prod/site.css",
    "maxSize": "15 Kb"
  },
  {
    "path": "./web/asset/prod/checkout.js",
    "maxSize": "15 Kb"
  },
  {
    "path": "./web/asset/prod/checkout.css",
    "maxSize": "15 Kb"
  }
] 

 WARN  files: [
  {
    "maxSize": 15360,
    "path": "./web/asset/prod/site.js",
    "size": 5904
  },
  {
    "maxSize": 15360,
    "path": "./web/asset/prod/site.css",
    "size": 7922
  },
  {
    "maxSize": 15360,
    "path": "./web/asset/prod/checkout.js",
    "size": 2164
  },
  {
    "maxSize": 15360,
    "path": "./web/asset/prod/checkout.css",
    "size": 8984
  }
] 

 WARN  token exists: true 

 WARN  repo: "XXX/YYY" 

 WARN  sha: "c1e95b8a2ddfd3481ea06baca4caae27e43c9804" 

 WARN  api enabled: true 

 WARN  fetching values: "..." 

Unhandled Promise

TypeError: Cannot read property 'data' of undefined

    at axios.get.then.catch.error (/home/travis/build/XXX/YYY/node_modules/bundlesize/src/api.js:38:46)

    at process._tickCallback (internal/process/next_tick.js:109:7)

$ node deploy/travis.github.js

Check if a pending status was added
```

**Comment by siddharthkp** [comment]
Whoops, bad timing:

https://twitter.com/zeit_status/status/897775014396743680

**Comment by iGitScor** [comment]
Hi,

the log changed

```
 WARN  token exists: true 

 WARN  repo: "1001Pharmacies/marketplace" 

 WARN  sha: "c1e95b8a2ddfd3481ea06baca4caae27e43c9804" 

 WARN 27m api enabled: true 

 WARN  fetching values: "..." 

 WARN  master values: {} 

 PASS  ./web/asset/prod/site.js: 5.77kB < maxSize 15kB gzip 

 WARN  message: "./web/asset/prod/site.js: 5.77kB < maxSize 15kB gzip" 

 PASS  ./web/asset/prod/site.css: 7.74kB < maxSize 15kB gzip 

 WARN  message: "./web/asset/prod/site.css: 7.74kB < maxSize 15kB gzip" 

 PASS  ./web/asset/prod/checkout.js: 2.12kB < maxSize 15kB gzip 

 WARN  message: "./web/asset/prod/checkout.js: 2.12kB < maxSize 15kB gzip" 

 PASS  ./web/asset/prod/checkout.css: 8.77kB < maxSize 15kB gzip 

 WARN  message: "./web/asset/prod/checkout.css: 8.77kB < maxSize 15kB gzip" 

 WARN  url: "https://bundlesize-store.now.sh/build?info=%7B%22files%22%3A%5B%7B%22maxSize%22%3A15360%2C%22path%22%3A%22.%2Fweb%2Fasset%2Fprod%2Fsite.js%22%2C%22size%22%3A5904%7D%2C%7B%22maxSize%22%3A15360%2C%22path%22%3A%22.%2Fweb%2Fasset%2Fprod%2Fsite.css%22%2C%22size%22%3A7922%7D%2C%7B%22maxSize%22%3A15360%2C%22path%22%3A%22.%2Fweb%2Fasset%2Fprod%2Fcheckout.js%22%2C%22size%22%3A2166%7D%2C%7B%22maxSize%22%3A15360%2C%22path%22%3A%22.%2Fweb%2Fasset%2Fprod%2Fcheckout.css%22%2C%22size%22%3A8984%7D%5D%2C%22repo%22%3A%221001Pharmacies%2Fmarketplace%22%2C%22branch%22%3A%22debug%2Fbundlesize%22%2C%22commit_message%22%3A%22Merge%20c1e95b8a2ddfd3481ea06baca4caae27e43c9804%20into%20033c8f080815847ec8f4683ff7127e599bc5f80b%22%2C%22sha%22%3A%22c1e95b8a2ddfd3481ea06baca4caae27e43c9804%22%7D" 

 WARN  global message: undefined 
````
I think I may have an explanation. The file is not committed, it is generated during the build, does it could break size comparison ?

**Comment by siddharthkp** [comment]
> The file is not committed, it is generated during the build, does it could break size comparison ? 

Nope, that shouldn't make a difference.

I think I'll need more information about your app, do you mind [DMing me](https://twitter.com/siddharthkp)?

I'll close the issue here.
